import Head from 'next/head';
import Image from 'next/image';
import BrandShowcase from '../components/BrandShowcase';
import Footer from '../components/Footer';
import Header from '../components/Header';
import ProductPlacement from '../components/ProductPlacement';
import ReveiwCardComponent from '../components/ReveiwCardComponent';
import StatsAndReviews from '../components/StatsAndReviews';

export default function Home() {
  return (
    <div className="flex flex-col">
      <div className="relative">
        <Head>
          <title>Plasticity</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <ProductPlacement />
        <div className="absolute bottom-0 bg-gradient-to-t from-[#d9dcee] h-1/3 w-full hidden lg:block"></div>
      </div>
      <BrandShowcase />
      <StatsAndReviews />
      <ReveiwCardComponent />
      <Footer />
    </div>
  );
}
